plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.magcode.hoodonnxtest'
    compileSdk 34

    defaultConfig {
        applicationId 'com.magcode.hoodonnxtest'
        minSdk 27
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    packaging {
        resources {
            excludes += ['META-INF/*']
        }
    }
}

dependencies {
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.19.0'
}
